name: Testing
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Latest Version
            os: ubuntu-latest
            python-version: '3.12'

          - name: Oldest Version
            os: ubuntu-latest
            python-version: '3.8'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Cache testing Dataset
        shell: bash -el {0}
        run: |
          export COBAYA_PACKAGES_PATH=./cobaya_packages
          cobaya-install wmaplike.WMAPLike

      - name: Run Tests
        shell: bash -el {0}
        run: |
          pytest -v
